- fabfile.py
Pass all patches as arguments and only call `git am` once
> Atomic `git am`

- README.md
- apply_pr/cli.py
Add `--host` option to parse url
> Add option to parse url

- apply_pr/fabfile.py
> Add check_pr

- apply_pr/cli.py
- setup.py
Fixes https://github.com/gisce/apply_pr/issues/18
> Add cli for check_pr

- apply_pr/cli.py
- apply_pr/fabfile.py
- setup.py
Show PR's info from list of PR 
It shows:
- State
- Merged at
- Milestone
> Check prs status

- apply_pr/fabfile.py
> Add feedback when the repo is not on rolling

- .gitignore
- Adds the deploy directory used by apply_pr to the gitignore
> Add deploy dir into gitignore

- apply_pr/fabfile.py
> Always raise an exception on fail

- apply_pr/fabfile.py
Now we can deploy withou tests being passed (show the :rocket: )
> Let deploy without tests pass

- apply_pr/__init__.py
- apply_pr/cli.py
- apply_pr/version.py
Run away from using an outdated version of apply_pr
> Check version of apply_pr

- README.md
- apply_pr/cli.py
Instructions of server restart was outdated, this PR only make's little changes in these.
> Modificación en las instrucciones a la hora de resetear el servidor

- apply_pr/cli.py
- apply_pr/fabfile.py
Enable to force hostname when apply_pr
> Apply_pr force hostname

- apply_pr/fabfile.py
Show list of changes applied on tag version
> Change LOG from milestone show PRs and issues

- apply_pr/cli.py
- apply_pr/fabfile.py
- setup.py
New function to create changelog from milestone
----
Adds the `create_changelog` command
```
Usage: create_changelog [OPTIONS]
Options:
-m, --milestone TEXT    Milestone to get the issues from (version)
[required]
--issues / --no-issues  Also get the data on the issues  [default: False]
--changelog_path TEXT   Path to drop the changelog file in  [default: /tmp]
--owner TEXT            GitHub owner name  [default: gisce]
--repository TEXT       GitHub repository name  [default: erp]
--help                  Show this message and exit.
```
> Create new function to create versions md

- setup.py
force fabric<2.0 into `setup.py` file
> Fix force to fabric<2.0

- apply_pr/fabfile.py
Imporvements
- Adding labels
- Adding hr at end of PR
- Filter custom att begin
> Improve detailed changelog

- .travis.yml
- Improve testing by replacing the "`pip install -e .`" with the full build and install "`python setup.py install`"
- Improve testing with py3 container
> IMP Testing install and python version

- README.md
> IMP README.md with usage and better explanation

- apply_pr/fabfile.py
On generate changelog command:
- Use custom file path on detailed file too
- Improve logging messages specifying all files written
> Improve changelog generation

- apply_pr/fabfile.py
Use pagination to get +100 Commits from a PR.
Closes #12
> ADD github pagination support to get PR commits

- apply_pr/fabfile.py
- Fix no `link` header when less than 100 commits
- Use method to get all commits
- Update all commit-getter methods to use this method
> Fix commit getting with new method

- setup.py
> Bump to v2.0.0

- apply_pr/cli.py
- apply_pr/fabfile.py
Add param `sudo_user` to allow local sastre deploy
The following params are needed:
`deploy --host ssh://username@localhost --src /path/to/folder/where/folder/erp/is/located --sudo_user username --pr PRNUM`
> Add param `sudo_user` to allow local sastre deploy

- apply_pr/fabfile.py
- IMP milestone print by sorting them
- IMP TO_APPLY by avoiding duplicates with set
> ADD sorted to check prs prints

- apply_pr/cli.py
Add named params on apply_pr function for programatically calls
> Add default parameters on apply_pr

- apply_pr/cli.py
- apply_pr/fabfile.py
Add auto_exit to deploy prs to server.
Add return values to get info when using apply_pr via code
> Add auto_exit ecosystem

- apply_pr/fabfile.py
- ADD new page: `TOP FEATURES`
- ADD main label: `GAS`
- ADD skip label: `traduccions`
> IMP Changelog

- apply_pr/cli.py
Set `get_deploys` tool description
> Set get_deploys description

- .gitignore
> Update gitignore to add .vscode dir

- apply_pr/cli.py
Change parameter milestone -> version on `check_prs`
> Change milestone to version on cli parameters

- apply_pr/fabfile.py
Add section with oficina virtual
> Add Oficina virtual on changelog

- apply_pr/fabfile.py
Order get_deploys as it is in github.
It is ordered from old to new
> Sort get_deploys

- apply_pr/fabfile.py
Add label "deployed" when mark as success any PR
> Add label on PR when mark as succes

- apply_pr/cli.py
- apply_pr/fabfile.py
* Change default value for auto-exit parameter
* Add print curl to download PRS to redeploy for (COPY-PASTE)
> Auto exit true and print curl command

- apply_pr/fabfile.py
With this fix sitecustomize is not needed anymore.
> Fixes encoding bug which sitecustomize was needed

- apply_pr/cli.py
New command:
```
$ sastre mark_deployed --pr=XXXX --host=ssh://user@host
```
> Add method to mark as deployed

- apply_pr/cli.py
- apply_pr/fabfile.py
Get the last success deployment and get de `from-commit` to re-deploy
> Add re-deploy feature

- apply_pr/cli.py
- apply_pr/fabfile.py
* Save diff into folder pr_number
* Enable deploy a list of separated "PR PR PR"
> Improvement apply pr 

- apply_pr/cli.py
- apply_pr/fabfile.py
Add `reject` option to redeploy PRs using diff method
```
sastre deploy --repository=erp --sudo_user=gjulia --src=/home/gjulia/src --prs="XX XX XX" --host=gjulia@localhost --as-diff --reject
```
For skip apply nothin
> Deploy with diff using reject option

- apply_pr/cli.py
- apply_pr/fabfile.py
`--skip-rolling-check` Default: False
> Option allow skip rolling mode check

- apply_pr/cli.py
- apply_pr/fabfile.py
> Add option --no-set-label, avoids label PR

- apply_pr/fabfile.py
- requirements.txt
Check prs using giscemultitools
> Check prs using giscemultitools

- apply_pr/fabfile.py
> Avoid inactive deployments

- apply_pr/fabfile.py
- requirements.txt
Ordena por `mergedAt` de menor a mayor si la tiene si no esta meged se tiene en cuenta como si tubiera `mergedAt = 2999-12-27T06:22:04Z` para que vaya al final, entre estas se ordenara por `createdAt`
> Imp prs sort

- apply_pr/fabfile.py
No incluir en las PR para volver a redesplegar las PR que estan CLOSED
> Skip CLOSED PRS to redeploy and show at the end

- apply_pr/fabfile.py
Change detailed link for new versions
> Fix detailed link when create changelogs

- apply_pr/cli.py
- apply_pr/fabfile.py
- requirements.txt
> PY3 compat

- apply_pr/fabfile.py
Ensure deploy/patches exist before diff apply
> Ensure deploy/patches on first diff apply

- apply_pr/fabfile.py
Decode output from command to 'utf-8'
> Decode command

- apply_pr/fabfile.py
Que el decode sea compatible en python 2 y 3
> Fix decode

- apply_pr/fabfile.py
> To apply pr if is on Error state in project version

- apply_pr/exceptions.py
- apply_pr/fabfile.py
> Fix diff apply to work correctly and show failuers + verbose

- apply_pr/fabfile.py
> Show errors before not included with disclaimer

- apply_pr/github_utils.py
- requirements.txt
This pull request includes significant changes to the `apply_pr/github_utils.py` file to enhance GitHub token validation and introduce OAuth login functionality. The most important changes include the addition of new imports, modifications to the `validate` function, and the implementation of the `oauth_login` function.
Enhancements to GitHub token validation:
* Added new imports: `time`, `os`, `logging`, and `qrcode` to support OAuth login and QR code generation.
Modifications to `validate` function:
* Updated the `validate` function to handle cases where the GitHub token is not present, by invoking the new `oauth_login` function to obtain a token and set it in the environment.
Implementation of OAuth login:
* Introduced the `oauth_login` function to facilitate device code flow for …
> feat: add oauth support
