fabfile.py
*^When commit text is long, filenames are too long.
=> FIX Short filenames

fabfile.py
In some cases (i.e test fails), the github deployment fails.
**TODO**
=> IMP Deploy even if gihub_deploy fails

fabfile.py
The default page size is 30 and the maximum is 100.
=> Up to 100 the page size of github API commits request

apply_pr/fabfile.py
After large email talking with Github Team
> 
> Hi Guillem,
> 
> Thanks for hanging in there. After conferring with another colleague about this, I'd like to share our findings with you.
> 
> When you create a deployment for some commit (let's call it X), a deployment issue event is created on all pull requests that have X as the head commit.
> 
> In gisce/erp#3626, it looks like you created a deployment on the oldest commit, be68d35, instead of the head commit, 83ab503:
> 
> https://api.github.com/repos/gisce/erp/deployments/10929258
> 
> GitHub doesn't currently create an issue event for this because be68d35 isn't the head commit.
> 
> The behavior you've observed is expected for now, but I can see how this can be confusing.
> 
> I've opened an issue internally so the team working on …
=> FIX mark to deploy using latest commit from PR

apply_pr/cli.py, apply_pr/fabfile.py, setup.py
This pr add two functionalities:
1. Update the status from a deploy
`$ status_pr --deploy-id=3424324 --status=success`
2. Get the deployments from the current branch
`$ fab -f apply_pr/fabfile get_deploys:PR_NUMBER`
Maybe in a future create a command line util for the last point, but we need a refactor to get only a one apply_pr and subcomands
=> Add function to set status

apply_pr/fabfile.py
Some times the PR are not marked as deployed due to some failure or maybe we need to mark a PR as deployed, so this new task helps.
=> Add mark_deployed task

apply_pr/fabfile.py
Before, when the url for the host was incorrect we didn't say anything.
Now we prompt the corresponding error.
=> Added prompt on error connecting to specified host

apply_pr/cli.py, apply_pr/fabfile.py
Add "repository" "company" and "src" options:
- Repository for the repo name (default as "erp")
- Company for the owner name (default as "gisce")
- SRC for the repote path of the source code (default as "/home/erp/src" as it is hardcoded right now)
=> ADD usage for any repository of any owner for any remote path

requirements.txt
Due to the new Fabric API on v2.0 there are import errors invalidating the commands from Click.
Opened the ISSUE #50 to a future improvement of the Fabric usage
=> Fix Fabric requirement to v<2.0

apply_pr/cli.py, apply_pr/fabfile.py
Improve the "check_prs_status" command
- Remove "useless" comment of: "marking as deployed on github" when it wasn't marking anything
- Replace PPrint with for and print
- Use colours if version is provided
- Check version <= milestone of PRs
- ADD a "to apply" list with all the PRS not included in version
- ADD the `--version` parameter to check with PR's milestone
=> Improve the "check_prs_status" command

apply_pr/cli.py
Fix #59
Using `--force-hostname` should mark the Pull Request as deployed on github with the name passed as parameter instead of skipping the upload of the patches.
In the `cli.py` file it is passing `force_hostname` as 4th parameter where it should be the 5th
https://github.com/gisce/apply_pr/blob/a1de8a175e30790950b7ffdd4d59345c3fe22898/apply_pr/cli.py#L49-L53
https://github.com/gisce/apply_pr/blob/d497a9f9e994b39037ea085a9ea73c2f1085c2f7/apply_pr/fabfile.py#L432-L435
=> Fix hostname parameter using force-hostname option

MANIFEST.in, setup.py
Write the dependencies of the library in a single `requirements.txt` file in order to avoid changing `setup.py` and `requirements.txt` files when a dependency has changed.
=> Use requirements.txt file to install the library

apply_pr/fabfile.py
The `git am` command, creates the directory "`.git/rebase-apply/`" and deletes it when completed.
Using `git am` when another session is running, fails.
Using `apply_pr` when a `git am` session is running is being catched as applying the commits and results in both am sessions being "applied" but the code is wrong for both sides as it'll probably be skipped or aborted.
ADD check for currently active am sessions. (Checks if the path "`.git/rebase-apply/`" exists. If it does exist, the repository is on a git am session and apply_pr will fail)
=> ADD Check for git am sessions before starting one

README.md, apply_pr/cli.py, setup.py
Allow to use `apply_pr` as `sastre` or `tailor`.
See `sastre --help` or `tailor --help`
```bash
$ sastre --help
Usage: sastre [OPTIONS]
Options:
--owner TEXT           GitHub owner name  [default: gisce]
--repository TEXT      GitHub repository name  [default: erp]
--host TEXT            Host to apply  [required]
--src TEXT             Remote src path  [default: /home/erp/src]
--pr TEXT              Pull request to apply  [required]
--from-number INTEGER  From commit number
--from-commit TEXT     From commit hash (included)
--force-hostname TEXT  Force hostname
--help                 Show this message and exit.
```
=> Add sastre and tailor CLI options for apply_pr

apply_pr/fabfile.py
When a PR is on ERROR state, the URL given to check it was hardcoded
When a PR is on ERROR state, the URL given to check it is build based on owner and repository
=> Fix Message shown on Check PRs Error

apply_pr/fabfile.py
The milestones of the PRs are sorted with using inorder tree sorting, which isn't user-friendly (from `dict.keys()`)
The milestones for the PRs are sorted alphabetically (from `sorted(dict.keys())`)
=> IMP printed result for Check PRs subcommand

apply_pr/fabfile.py
>In [#66 ADD Check for git am sessions](https://github.com/gisce/apply_pr/pull/66) we added a check for current am session.
Checking for am sessions does not work for the following case:
_As the Download/Upload of patches may delay the am session start, if two users deploy the check may pass on both and after the "git am" they'll encounter the same failure as described in #66 ._
- Add a check for am sessions just before applying the patches
- Do not remove the initial check (it'll be faster than downloading, uploading and then checking)
=> ADD check for am session an instant before applying patches

apply_pr/fabfile.py
Remove the path of the deploy cache path before usage to avoid uploading unupdated patches.
=> Remove the path of the deploy cache before usage

apply_pr/cli.py
Connection port wasn't used so no connection could be established via non-standard port.
Following the standard of connections as explained [here](https://tools.ietf.org/id/draft-salowey-secsh-uri-00.html)
This improvement allows connections, allowing port usage like:
```
sastre deploy --host ssh://user@hostname.server:1234
```
As we are not using the connection method, we also used the default port for ssh (22) and added the default scheme for `ssh`. With this improvement, one can deploy like:
```
sastre deploy --host user@hostname.server
```
=> ADD Port and Set default scheme (ssh) from Connection URI.

apply_pr/cli.py, setup.py
- Make all multiple options a combined list in top of the script as it was for the `apply_pr` command
- Replace "`tailor`" group to "`sastre`"
- DEL tailor command
- Now only `sastre` is available as it will be the final name of the command/package
- The `apply_pr` command is still available
- Now it uses arguments instead of options, being it's usage as `sastre status deploy-id status`
- Status argument defaults to "success" (the most common status used by this command), so it's not a required argument. Help continues to show the options.
- ~~Added a description to show on help~~ Done in https://github.com/gisce/apply_pr/pull/86
- The command now uses an argument instead of an option, being it's usage as `get_deploys pr`
=> IMP Sastre usage

apply_pr/fabfile.py, requirements.txt
Version and mileston were compared as strings, so "v2.99" was greater than "v2.100".
This PR uses packaging.version to parse and compare version tags.
=> Use packaging.version to compare versions

apply_pr/cli.py, apply_pr/fabfile.py
Enable two functions on console command `sastre deploy`
* **force-name**: Different repository folder name, _default None_
* **auto_exit**: Mark as error and do `git am --abort` when deploying PR has conflitcs, _default False_
```
sastre deploy --pr XXX --host=ssh://USER@HOST --force-name=erp_distri --auto-exit=True
```
closes #89 duplicate
=> Deploy PR on different repository folder name 

apply_pr/fabfile.py
This resolves two strings that need to be decoded from 'utf-8' when applying patch.
=> Fix encoding on applying patch message

apply_pr/fabfile.py
- Fix the function that retrieves and lists all deployments from a PR in a repository.
- URL now uses `sha` parameter instead of `ref`, avoiding `502` error on GItHub API requests.
- From https://docs.github.com/en/rest/reference/repos?query=Deployemt#list-deployment
=> Fix 'get_deploys' function

apply_pr/fabfile.py
When you operate in a directory without permissions you get a simple feedback.
Errors are previously masked.
=> Get error message when try to write in unpermission directory

apply_pr/fabfile.py
When generate diff in some git versions not generate diff file:
Change method passing user as sudo user to generate diff.
=> use sudo user to generate diff

apply_pr/cli.py, apply_pr/fabfile.py
Now is possible to do:
```
sastre deploy --pr=https://github.com/gisce/erp/pull/15395 --host=user@somehost--environ=pro
```
And deploy from a commit using
```
sastre deploy --pr=https://github.com/gisce/erp/pull/15395/commits/aed98389b88c4bbd000d31118e392c4c1fd23d03 \
--host=user@somhost--environ=pro
```
And the pr_number, owner, repository will be extracted from the pull-request url
=> Allow pass url for pr number

apply_pr/fabfile.py
Always set old_prefix before doing apply by diff and restore at end of command
``` diff
@@ -195,10 +195,9 @@ class PatchApplier(object):
else:
reject = ''
print(colors.green('Applying diff {}'.format(diff)))
+            old_prefix = env.sudo_prefix
+            env.sudo_prefix = "sudo -H -S -p '%(sudo_prompt)s' "
if reject:
-                from fabric.api import run, env, prefix
-                old_prefix = env.sudo_prefix
-                env.sudo_prefix = "sudo -H -S -p '%(sudo_prompt)s' "
try:
sudo(
"git apply {}{}".format(diff, reject),
```
=> FIX when restorning old prefix

apply_pr/cli.py
if `--exit-code-failure` flag enabled on sastre deploy, exits program with 1 if had failed deploys
=> Option to get exit code 1 on apply failure

apply_pr/fabfile.py
Las PRs mergeadas sin milestone no se estaban incluiendo en el listado de reaplicación
=> PRs without milestone as ERROR (check_prs)

apply_pr/fabfile.py
Poder deshabilitar el modo sudo a través de la variable de entorno `APPLY_PR_NO_SUDO_MODE`
Caso de uso:
Usuario local sin permisos de super usuario y con su propia clave ssh publica añadida en el listado de autorizadas
=> disable sudo mode by env

apply_pr/fabfile.py
Change the repository check error message so that it is more explicit. Useful when some implicit arguments such as `repository` or `src` should be changed, making the tool more verbal and accessible.
Before:
After:
=> More explicit repository not found error message

apply_pr/fabfile.py
Fix comparing an unicode text with a bytes string and when decoded an error is raised if is decoded with default encoding ('ascii')
=> Fix comparing unicode to decoded text

apply_pr/fabfile.py
Raise explicit error mesage on any github token issue. Before it threw unexpected errors in the code,
=> Raise explicit errors on github token not provided or expired
